[build]
  command = "npm i && cd functions/notify && npm i && cd .. && npm run encrypt-secrets && npm run inject-secrets "
  functions = "/functions"

[[redirects]]
  from = "/notify"
  to = "/.netlify/functions/notify"
  status = 200